export const enum ERoutesNames {
  DEFAULT = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  RESET = "/reset",
  DASHBOARD = "/dashboard",
  DASHBOARD_UTILISATEURS = "/dashboard/utilisateurs",
  DASHBOARD_EDITION = "/dashboard/utilisateurs/edition/:id",
  DASHBOARD_BASE = "/dashboard/base",
  DASHBOARD_CONTROLE = "/dashboard/controle",
  DASHBOARD_WORKFLOW = "/dashboard/workflow",
  DASHBOARD_ALERTES = "/dashboard/alertes",
  DASHBOARD_ROLES = "/dashboard/roles",
  DASHBOARD_PREFERENCES = "/dashboard/preferences",
  DASHBOARD_CALENDRIER = "/dashboard/calendrier",
}
